
print("===== Resume  =====")

## input details
name = input("Enter your full name: ")
email = input("Enter your email address: ")
phone = input("Enter your phone number: ")
address = input("Enter your address: ")
objective = input("Enter your career objective: ")
education = input("Enter your educational background: ")
skills = input("Enter your skills (comma separated): ")
work_experience = input("Enter your work experience (if any): ")
hobbies = input("Enter your hobbies (comma separated): ")
character_reference = input("Enter character reference (name, num): ")

## output resume
print("=================================")
print(" "+ name + "'s"+ " " +"Resume         ")
print("=================================")
print("Name       :", name)
print("Email      :", email)
print("Phone      :", phone)
print("Address    :", address)
print("Objective  :", objective)
print("Work Exp.  :", work_experience)
print("\n--- Education ---")
print(education)
print("\n--- Skills ---")
print(skills)
print("\n--- Hobbies ---")
print(hobbies)
print("\n--- character reference ---")
print(character_reference)
print("===========================")
